language: java
deploy:
  provider: releases
  api_key:
    secure: VJF3ba/Rm3dFNdxjAVdIt9QA1CNVrOOKosx8/0CnPaOwXntdT4RwSr8264ZdcAj+SvDbisLyKgRxRue5YLD3vE8RF4HUpuGWrOG3xUTlyy7Qj83+LEaPOXrQXLzOW2Nkaz1gTQ2dxzc62ewJn85hQLNnLjbByj31LLWywGHISKHvbQEUPbb+6tJmhJTC+HvzznxjfJeFmQcFtjL0ykL6xPObNCJvYzh6Kkly2QKWDd4NnRL16ga7JvZP08PTB22N+xlcQlGsz7em1Gpdd3MB7MJWuEzJhF/j7KyMd43LXuo6spm4PwO4OqkK4jXveG/zTOgv6M59h9TyDDinVv87eCixcC7+blxAWVyvpnEhl/+n2bhU29zHG/qk4oT3JVx808T+7f5PmTjHVv10Bu4RP9eHx0BO8bIIgh3WjF8qkL1eTe+KMP0Q2TBiBfuLKmu3C3S1EqN6hKdcwcDk5U10nKOXVmf8u8X6aL1q6sSLUR4+3eOuK+xxixqPgpVhRSYtp8dH2uaNySJoXwTSXJ7wyicfO7i9hRyjkcDFglJ55c/5h1b7nWhXE+3nzG11gKNHDs+Kx6g0koc+nbpHAepRBSG8E5cxeo5qxpKgZGjq8GlsgedL8LcfTN4Pv+mD6FQYkI2hBMChy0ATdUnxKa8tpALa8h3iO53kS0yIBHGautQ=
  file: build//distributions/xld-controlm-plugin-1.0.1.xldp
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-controlm-plugin
notifications:
  slack:
    secure: Di6fxR1tFJfUZsuvBeLLPqKdYD3n7/kW02kwn4qDv+oQT6gfxVuujuJ+0wibKENtAYfGDhN1AQyNuYQC79nKoClrkfgglzVi4xwYksbxXzIZsO3an9+S1kzZhUFQqmuGAL8TLpk35jDoFJCOoL7I0kkbsVrKEgGQa8YSWsAbu6fkDCAbvFIUdmsfcFKoJzkvDF/OQk7D/jIb1sP+t3xrOh3OvdtDrOfVku/N9/Dqa6+V3XKZU2yhOJSCz6j5sYxTIcZBvFlFiV8QSoKzC6/YLJmhK5m5R28DJkix9ND+tYyllT0LB0Ov6OkHCBfKaj3yryVt7JxyGQenZfrLdTlfB8U2ifrqkfhZ1N03OrfC9yTkNZ7+vEnOuCMHSLyXKNGB6l33PE+FYpFS703HD0kT31FV02Efdlv6XLIiLA6KL5rpAwCEGjuW64VqLO8aXK5KrsiFSxE+Jgo4cLHmXSAjCKxp8i9i3NUVICRvDglcee/BG5L3GlM0fguMqIhVpqiqJudCBG3Dlrx6B6UFcBGFmNBwRL0m5F3UV5F7ZcAgs9/rc026SNVUbfw6J+w5pjGZXr4c0g8b+rkok/RouvO2lMmzOuCTdGEHIz6EQVvuUKHHyUjuATOLn3gRNgahth8NO4lLlNaQ3fn08hAC95JJfl08VwpF6Gg3R1gc+eeRSCI=
